SELECT 1 ID_INVENTARIABLE, 'INVENTARIABLE' DESC_INVENTARIABLE FROM DUAL
UNION ALL
SELECT 0 ID_INVENTARIABLE, 'NO INVENTARIABLE' DESC_INVENTARIABLE FROM DUAL
UNION ALL
SELECT -1 ID_INVENTARIABLE, 'No Configurada' DESC_INVENTARIABLE FROM DUAL

