SELECT 1 ID_TIPO_ZONA, 'GUARDADO' TIPO_ZONA FROM DUAL
UNION
SELECT 2, 'PULMON' FROM DUAL
UNION
SELECT 3, 'ANDEN' FROM DUAL
UNION
SELECT 4, 'INUTILIZADO' FROM DUAL
UNION
SELECT 5, 'PUNTERA DE RACK' FROM DUAL
UNION
SELECT 6, 'CONTROL' FROM DUAL
